// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/MuxiKeStack/be-user/grpc"
	"github.com/MuxiKeStack/be-user/ioc"
	"github.com/MuxiKeStack/be-user/pkg/grpcx"
	"github.com/MuxiKeStack/be-user/repository/cache"
	"github.com/MuxiKeStack/be-user/service"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	client := ioc.InitRedisClient()
	cmdable := ioc.InitRedisCmd(client)
	userCache := cache.NewRedisUserCache(cmdable)
	redsync := ioc.InitRedSync(client)
	userRepository := ioc.InitUserRepository(db, userCache, logger, redsync)
	userService := service.NewUserService(userRepository)
	userServiceServer := grpc.NewUserServiceServer(userService)
	clientv3Client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxKratosServer(userServiceServer, clientv3Client, logger)
	return server
}
