mysql:
  dsn: "root:root@tcp(localhost:3306)/kstack"

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12379"

grpc:
  server:
    name: "user"
    weight: 100
    addr: ":8091"
    etcdTTL: 60

